### ISSUE TITLE
precompiled npm failed to install puppeteer

### ISSUE THREAD

**Issue by antonioCoco** [phra/crosser#6]
Hi @phra,
i have just downloaded a compiled version from node.js --> https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz
i copied it in /opt/node and added 3 soft links in /usr/bin/npm /usr/bin/npx and /usr/bin/node pointing to the binaries in the directory /opt/node/bin/.

Running the following command as root:

`npm i -g @phra/crosser`

I got the following error on puppeteer installation:

<pre>/opt/node/bin/crosser -&gt; /opt/node/lib/node_modules/@phra/crosser/bin/run

&gt; puppeteer@1.17.0 install /opt/node/lib/node_modules/@phra/crosser/node_modules/puppeteer
&gt; node install.js

ERROR: Failed to download Chromium r662092! Set &quot;PUPPETEER_SKIP_CHROMIUM_DOWNLOAD&quot; env variable to skip download.
{ Error: EACCES: permission denied, mkdir &apos;/opt/node/lib/node_modules/@phra/crosser/node_modules/puppeteer/.local-chromium&apos;
  -- ASYNC --
    at BrowserFetcher.&lt;anonymous&gt; (/opt/node/lib/node_modules/@phra/crosser/node_modules/puppeteer/lib/helper.js:110:27)
    at Object.&lt;anonymous&gt; (/opt/node/lib/node_modules/@phra/crosser/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: <font color="#C4A000">-13</font>,
  code: <font color="#4E9A06">&apos;EACCES&apos;</font>,
  syscall: <font color="#4E9A06">&apos;mkdir&apos;</font>,
  path:
   <font color="#4E9A06">&apos;/opt/node/lib/node_modules/@phra/crosser/node_modules/puppeteer/.local-chromium&apos;</font> }
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> puppeteer@1.17.0 install: `node install.js`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the puppeteer@1.17.0 install script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /root/.npm/_logs/2019-05-30T18_27_56_413Z-debug.log
</pre>

My machine is a Kali GNU/Linux Rolling 2019.1
NodeJS version: v10.16.0
NPM version: 6.9.0

Am i missing something? Any idea on the resolution?

**Comment by antonioCoco** [comment]
Using "npm install" in the local folder of this repo solved this issue and installed everything successfuly!
